### ISSUE TITLE
IE11 images disappear when you scroll past and then back

### ISSUE THREAD

**Issue by EdwinLove** [eisbehr-/jquery.lazy#73] opened 2017-02-01 11:42 UTC
This plug in is working well in all other browsers but in IE11 it seems that when you scroll past the images and then scroll back to them they have disappeared and then pop back in again

**Comment by eisbehr-** [comment] 2017-02-01 11:54
Thank you for report it! Could you please create a fiddle reproducing the problem, so I can take a deeper look.

Thanks!

**Comment by EdwinLove** [comment] 2017-02-01 12:14
Thanks for replying so quickly, 

Can't get the fiddle to load in the images but this is a pretty accurate representation of the code
https://jsfiddle.net/zc8moo4m/ will carry on working at it to try to get it working

**Comment by EdwinLove** [comment] 2017-02-01 12:38
Fiddle https://jsfiddle.net/zc8moo4m/ is now working

**Comment by eisbehr-** [comment] 2017-02-01 15:38
Is it possible that you send me the wrong fiddle in the second post, or forgot to save your changes? :wink:
Because it's the same link and it's not working.

**Comment by EdwinLove** [comment] 2017-02-01 15:50
Ah, my apologies, not used to using fiddle. the updated url is https://jsfiddle.net/zc8moo4m/2/

**Comment by eisbehr-** [comment] 2017-02-02 07:21
Thanks for the fiddle! I checked it in multiple browsers, even IE11, and see no problems at all. Do you have the descriped issue in that fiddle too?

To be honest, I don't really think that this is a problem of the plugin. Because images loaded once will never be touched by Lazy again (they will be removed from the object). I have three possible answers causing that problem:

1. Your IE11/PC has problems handling base64 encoded images.
2. There is a special CSS handling some of this parts.
3. There is another javascript part in your page, touching the images.

Please give me some more details, maybe we find that problem!

**Comment by EdwinLove** [comment] 2017-02-02 09:49
OK, I have to confess I don't have IE (on a Mac) so was unable to check the fiddle had the same problem. We are deploying the code to a test url soon so I can send you a link to it in place, with all of the other css etc

**Comment by eisbehr-** [comment] 2017-02-24 07:54
I'll close this because of missing user input.

**Closed by eisbehr-** 2017-02-24 07:54 UTC
