### ISSUE TITLE
instance.loadAll() throws error

### ISSUE THREAD

**Issue by iwiszhou** [eisbehr-/jquery.lazy#25] opened 2015-06-22 04:22 UTC
Init when ajax fetch data.
window.lazy =  $("img.lazy").Lazy({
    		chainable: false
});

Trigger loadAll() when load more items form ajax. then call loadall in ajax callback.
window.lazy.loadAll();

Error***********
Uncaught TypeError: _event.e is not a function_instance.loadAll @ store.min.js:631g.updateImageLazyLoad @ store.min.js:781(anonymous function) @ store.min.js:828m.Callbacks.j @ store.min.js:2m.Callbacks.k.fireWith @ store.min.js:2x @ store.min.js:4m.ajaxTransport.send.b

**Comment by eisbehr-** [comment] 2015-06-22 14:21
Hello @iwiszhou,

i'm not able to reproduce this behavior. Also i'm not sure if you call this in correct manner. Might you create an example/fiddle for me? I would like to investigate on this ...

Thanks!

**Comment by iwiszhou** [comment] 2015-06-23 00:34
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>click demo</title>

  <script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.lazy/0.5.3/jquery.lazy.min.js"></script>
</head>
<body>

<div>
  <ul>
    <li><img class="lazy" data-src="http://jquery.eisbehr.de/lazy/examples/images/1.jpg?t=1435018746"></li>
    <li><img class="lazy" data-src="http://jquery.eisbehr.de/lazy/examples/images/2.jpg?t=1435018746"></li>
    <li><img class="lazy" data-src="http://jquery.eisbehr.de/lazy/examples/images/3.jpg?t=1435018746"></li>
  </ul>
</div>
 
<div><button id="loadall">Fire Loadall</button></div>
<div id="loadall-div">

</div>

<script>
$(document).ready(function() {
    window.lazy = $("img.lazy").Lazy({
      chainable: false
    });
});
$( "#loadall" ).click(function() {
  var html = '<ul>' +
    '<li><img class="lazy" data-src="http://jquery.eisbehr.de/lazy/examples/images/4.jpg?t=1435018746"></li>' +
    '<li><img class="lazy" data-src="http://jquery.eisbehr.de/lazy/examples/images/5.jpg?t=1435018746"></li>' +
    '<li><img class="lazy" data-src="http://jquery.eisbehr.de/lazy/examples/images/6.jpg?t=1435018746"></li>' +
  '</ul>';
  $('#loadall-div').append(html);
  window.lazy.loadAll();
});
</script>
 
</body>
</html>

**Comment by iwiszhou** [comment] 2015-06-23 00:36
Hi,
Below is the example I am running in the local. You can just download the or copy the whole html and run locally, you will see/reproduce the error.

https://gist.github.com/iwiszhou/69a4c16d6d19c8a268b4

Thanks!

**Comment by eisbehr-** [comment] 2015-06-24 08:27
Hello @iwiszhou,

i really don't understand what you want to archive with your script. Why do you call `loadAll`? This function will load only the already registered elements left, not the new elements loaded over ajax. 

The error you got when call `loadAll` is because all element are already loaded (the first three). I will fix this problem, but it will not affect the functionality.

**Comment by eisbehr-** [comment] 2015-06-24 09:02
Version 0.5.4 will fix the error on call `loadAll` and `update` after all images are loaded.
I'll close this issue. Let me know if you need more help.

**Closed by eisbehr-** 2015-06-24 09:02 UTC

**Comment by iwiszhou** [comment] 2015-06-24 16:34
Hi @eisbehr- 

Oh, I think I forget to describe what I am trying to do.

Let say, right now, I have a feature Pagination on my page. Every time, when user click the next page. It will fire an API call to fetch another 100 images' url from server. On the ajax callback, I will inject a new html content into my DOM. (for example, I will inject '<div><img data-src='http://exmaple.com/abc.jpg'></div>'
So, how I can render the image? 
Solution 1: should I destroy the existing 'lazy' instance and create a new one.
Solution 2: it there any ways I can reuse the existing 'lazy' instance to render the new image/html I just inject into my DOM?

Thanks

**Comment by eisbehr-** [comment] 2015-06-25 06:49
Hello @iwiszhou,

well, i think there are two possible ways to accomplish that, but there is no way to add more elements to an existing instance.

1.) Destroy the old instance and create a new one after every ajax load. Best way would be to remove the element class after loading so new instances would not get any already loaded elements. You can use the `afterLoad` callback to do this.

2.) Create a instance for every page. Let your ajax response add an unique class to the elements like `page-2`. So you can create an instance for the page: ```JS $('img.lazy.page-2').Lazy();```

Hope this will help you. And only use `loadAll` when you really want to load *all* images! ;)

**Comment by tsm91** [comment] 2015-11-15 11:29
Hi @eisbehr- i tried your 1st solution, but for some reason it doesn't lazy load ajax loaded images.

```js
  initLazyLoad() {
    this.lazyInstance = $('img.lazy').Lazy({
      chainable: false,
      afterLoad(img) {
        img.removeClass('lazy');
      },
      onFinishedAll() {
        this.destroy();
      }
    });
  }


  $.ajax({
      type: 'GET',
      url: location.setQueryParam('page', ++config.paginate.page),
      dataType: 'json',
      success: this.onShowMoreSuccess.bind(this),
      complete: this.initLazyLoad
    });
```

**Comment by eisbehr-** [comment] 2015-11-15 12:14
Hello,

do you got an example for me to see what went wrong? So far it looks 
good to me.

And you don't use the `onFinishedAll` callback to destroy an instance. 
There is a config paramter `autoDestroy`, wich is `true` by default. So 
every Lazy instance destroy itself by default.


Am 15.11.2015 um 12:29 schrieb Attila Egyed:

**Comment by tsm91** [comment] 2015-11-15 13:16
@eisbehr- sorry i deleted my comment, but i still have this problem. If the `lazyInstance` is going to be destroyed by the time ajax completes, it will not work. 

```js
export default class Comment {
  constructor() {
    this.initLazyLoad($('img.lazy'));
  }

  initLazyLoad($imgs) {
    this.lazyInstance = $imgs.Lazy({
      chainable: false,
      afterLoad(img) {
        img.removeClass('lazy');
      }
    });
    // going to be an empty array on 2nd init but $imgs argument has content [...]
    console.log(this.lazyInstance.getItems());
  }

  addLazyItems() {
    const $imgs = $('img.lazy');
    if (this.lazyInstance) {
      this.lazyInstance.addItems($imgs);
    } else {
      this.initLazyLoad($imgs)
    }
  }

  onShowMore() {
    this.showShowMoreLoader();
    $.ajax({
      type: 'GET',
      url: location.setQueryParam('page', ++config.paginate.page),
      dataType: 'json',
      success: this.onShowMoreSuccess.bind(this),
      complete: this.addLazyItems.bind(this)
    });
  }
}
```

**Comment by eisbehr-** [comment] 2015-11-15 13:34
Could you please create an new issue and not using a existing one? I will take a look on your problem in the meantime ...thanks!
