### ISSUE TITLE
Safari problem

### ISSUE THREAD

**Issue by ipetrov87** [eisbehr-/jquery.lazy#50] opened 2016-05-18 14:46 UTC
Hi, i am using this great plugin, but now i have a problem with it. When I open the page with Chrome everything is working. When i open the page with a Safari the images is not loaded. Sometimes the image is shown for a second but after that is gone. I have also ajax request that is build on #39. And after AJAX request is done all images are shown in Safari. I have been noticed one more strange thing.  When i initialize a plugin I am set `retinaAttribute : "data-srcx2"`, but when i check the the current instance setting I see `retinaAttribute : "data-retina"`. After AJAX request it is still `retinaAttribute : "data-retina"` but images are loaded.

**Comment by eisbehr-** [comment] 2016-05-18 15:09
Hello @ipetrov87,

could you create a [jsfiddle](https://jsfiddle.net) for me, where you can reproduce the problem? Then I would like to investigate. For now, the only idea i have, is a wrong use of the plugin. But that dosen't mean there could not be a bug. :wink: 

Thanks!

**Comment by ipetrov87** [comment] 2016-05-19 06:35
I try to create the jsfiddle, but no success. I use something like [this](https://jsfiddle.net/k1j9zasc/2/) but it is still working in all browsers. I have no idea what can be the problem. Do you have any ideas, what i can check?

**Comment by eisbehr-** [comment] 2016-05-19 06:57
So you could not recreate the problem? Well, I'm glad abaout that! ;)

The fact, that the images somethimes shows for a second but then disappear could be a indicator that some strange css kicks in. Or maybe you got some old js somewhere, doing it? Or maybe somthing with your responsive things? I saw the class `img-responsive` in your example.

Lazy would not touch an element again after it was handlet once. So if a image is loaded the plugin will not remove it. And you say the loading works fine too. To there is no generally problem. But without seeing the code and the problem it is very difficult to detect the issue ...

**Comment by eisbehr-** [comment] 2016-05-20 06:31
I close this here, because this seems not to be a problem of the plugin. Feel free to response, if you have any other questions left.

**Closed by eisbehr-** 2016-05-20 06:31 UTC

**Comment by ipetrov87** [comment] 2016-05-26 13:22
I was leave this problem for a while because there was some other more important stuff to do, but now i am back. I trying with this 

```
afterLoad: function(element) {
  console.log(element);
}
```

In console i get only 2 empty row, from first two images that should be loaded. Witch it strange for me. Then i start to scroll down the page so I expect to see more empty rows, but there is nothing like the Lazy is not triggered. If you have any idea what can be, or what to check just say. 

I also use onError event
```
onError: function(element) {
  console.log('error loading ' + element.data('src'));
}
```
but i don`t get any of them in console.

**Comment by eisbehr-** [comment] 2016-05-26 13:47
It's still hard to say without seeing the code. And it is only in Safari?
Any way to upload the page / code and let me take a look there?

**Comment by ipetrov87** [comment] 2016-05-26 13:54
I can give a link to the page, but page is still in development. Can you give some e-mail to send it to you?

**Comment by ipetrov87** [comment] 2016-05-26 14:22
I have check the page on IPhone 6S Plus it is the same.
With dev tools on IPhone 6S Plus i am abble to see that console prints this:
```
[0: <img id="product-collection-image-1298">]
  0 : img#product-collection-image-1298.img-responsive
  0 : img#product-collection-image-1298.img-responsive
```

On a windows Chotme i get only one img, like this:
```
[0: <img id="product-collection-image-1298">]
  0 : img#product-collection-image-1298.img-responsive
```

I am start to think some king of multiple jQuery import. I Make a search scripts and find that i have a `jquery-1.10.2.min.js` and `jquery-1.11.1.min.js`. But even if I remove one of then i still face same problem, and still see "Dublicated" images in console.

**Comment by eisbehr-** [comment] 2016-05-27 06:45
Yes, send it to jquery _at_ eisbehr _.de_.

**Comment by ipetrov87** [comment] 2016-05-27 07:21
You should get a email from me now.

**Comment by eisbehr-** [comment] 2016-05-27 08:36
Yes, it's here. Check your mails too. :wink:

**Comment by attrib** [comment] 2017-09-05 20:04
What was the solution here at the end?

Running in the same issue with Safari only. Would be good to know where I have to look into.

**Comment by eisbehr-** [comment] 2017-09-06 12:53
I'm not 100% sure anymore, but I think it was a missing `DOCTYPE` tag in the html document.

**Comment by ipetrov87** [comment] 2017-09-07 09:46
I think that in the example #39, that I use for AJAX calls, was missed to be added `bind: "event"` to configuration. Check [this answer](https://github.com/eisbehr-/jquery.lazy/issues/39#issuecomment-197263608). Let us know if that helps.

**Comment by oneextra** [comment] 2018-11-12 14:40
I encountered a similar problem (images load fine in chrome and FF but in Safari nothing happens) and after debugging could pin point it to Safari not triggering window's load event for some reason, or it is triggered earlier than my scripts (enqueued in Wordpress, very standard). 
This leads to _initialiaze never being called and images remaining empty. 

My workaround now is to trigger window load event manually after defining the lazy elements. Its not pretty, but it did the work for now.
