### ISSUE TITLE
Does not work at all in IE11 when using jQuery 3.0.0

### ISSUE THREAD

**Issue by catearcher** [eisbehr-/jquery.lazy#55] opened 2016-07-11 14:30 UTC
When using this library together with the current jQuery version (3.0.0), no images are lazy loaded in Internet Explorer 11.

It does work in Chrome with jQuery 3.0.0, and it also does work in IE11 with jQuery 1.x and 2.x, but it does **not** work in IE11 + jQuery 3.0.0.

The root of the problem seems to be that `$(window).on(_load + "." + namespace)` is not working anymore.

**Comment by eisbehr-** [comment] 2016-07-12 23:32
Hello @catearcher,

the plugin fully workes with jQuery 3. The Problem is the ready state of jQuery. Since 3.0 it is fully asynchron, witch means it can be triggered after '.load()'. I was asking exacty this to the jQuery Team, because in my eyes it is bad too. See the whole thread here: https://github.com/jquery/jquery/issues/3194#issuecomment-230562932

To solve your problems, remove the ready state around your plugin initialization.

**Comment by eisbehr-** [comment] 2016-08-02 12:27
This problem should be fixed as of version 1.7.2.

**Closed by eisbehr-** 2016-08-02 12:27 UTC
Labels: invalid, question
