### ISSUE TITLE
Use Lazy with CDN

### ISSUE THREAD

**Issue by Redani** [eisbehr-/jquery.lazy#61] opened 2016-08-17 21:24 UTC
Hi,
Sorry my message isn't really a bug but i didn't find where to write.
I'm already using your plugin and signed up for a CDN but it doesn't seem to be working in combinaison with Lazy, I'm using v0.6.4 and was wondering if there's a tweak for what i want to do.

Thanks a lot
Regards

**Comment by eisbehr-** [comment] 2016-08-18 07:06
Hello @Redani,

I'm not sure what your question is. Do you have problems using your own CDN, or using Lazy over a CDN? Please add a bit more detail, some code or a jsfiddle. It's hard to tell without any information.

Another note: YOu know that 0.6.4 is a really, really old version? Current version is 1.7.3.

**Comment by Redani** [comment] 2016-08-19 11:14
Dear @eisbehr- , thank you very much for your fast reply. Actually it's now working, all the lazy pictures are being loaded from the cdn! don't know why it didn't work before :|
OK, i'll update now to v1.7.3 and will let you know if anything goes wrong.

Best regards and once again thank for this lovely plugin ;)

**Comment by Redani** [comment] 2016-08-19 11:23
Hi again, it doesn't seem to be working, maybe because i'm using jquery 1.7 ?? I get this error: Uncaught TypeError: Cannot read property 'attr' of undefined

**Comment by eisbehr-** [comment] 2016-08-19 11:31
This is hard to say without seeing code or have an example for you. Sorry, I can't help you without providing me more information.

**Comment by Redani** [comment] 2016-08-19 12:07
Where can I PM a link to our website?

**Comment by eisbehr-** [comment] 2016-08-19 12:22
Please create a [fiddle](http://jsfiddle.net) recreatig the problem.

**Comment by eisbehr-** [comment] 2016-08-22 07:29
Closed because of missing user input.

Please feel free to answer on this issue or reopen it, if the problem remains and you want to add more details.

**Comment by Redani** [comment] 2016-08-22 11:53
Hi, sorry, was out this weekend.
here is a fiddle: https://jsfiddle.net/e6p4ke77/

**Comment by eisbehr-** [comment] 2016-08-22 12:11
I don't know what the `jquery.tools.min.js` is. But it seems that jQuery is missing. When adding it everything workes fine. And keep in mind, that `https://cdn.jquerytools.org/1.2.6/full/jquery.tools.min.js` seems to have a problem with `https`. So it is not loading on jsfiddle.

So the problem is not Lazy. Everything works fine. Maybe contact jQuery Tools cdn or take a look at the code. It not belongs to my plugin. :wink: 

https://jsfiddle.net/e6p4ke77/2/

And it seems that the

**Comment by Redani** [comment] 2016-08-23 12:17
jquerytools is a js framework that already contains already jquery 1.7.1. I have updated the fiddle with a new version that supports SSL: https://jsfiddle.net/e6p4ke77/4/

**Comment by eisbehr-** [comment] 2016-08-23 13:46
Ahh, there you got the problem. jQuery 1.7.1 has some bugs they fixed withing 1.7.2. So the minimum requirement for Lazy is 1.7.2, as you can [read in the docs](https://github.com/eisbehr-/jquery.lazy#compatibility). You have to use a newer version of jQuery. And keep in mind, jQuery 1.7.2 is from 2011! You really should update to newser version.

**Closed** 2016-08-23 13:47 UTC
Labels: invalid

**Comment by Redani** [comment] 2016-08-25 12:50
OK :( and what is the latest version of Lazy that supports jquery 1.7.1 ?

**Comment by eisbehr-** [comment] 2016-08-25 13:17
I don't know if there is a version running with 1.7.1, because this version of jQuery got these bugs.

I would really, really recommend you to update to another version and **don't** use jQuery Tools! The tools haven't been updated within the last two years. They are yout of date and will possible have bug on newser browsers too. Search for alternatives and use a newer version of jQuery too. 1.7.1 is even over 5 years old and has different problems.

Really, don't use both anymore!

**Comment by Redani** [comment] 2016-08-25 14:08
I understand, but the problem is that i use way too much jquerytool (form validators, overlays, tooltips, ...), i'll need so much time to convert everything with a newer version!!
do you recommend any good and complete jquery framework? what you think about jQuery UI ?
thanks for your advices

**Comment by eisbehr-** [comment] 2016-08-25 14:22
Yes, but your jQuerytools are now so old, it is time to go on and redone anything you use. And jQuery already is a framework. :wink: 

jQuery UI is not a bad idea. It is from the same developers and will be updated in the future.

**Comment by Redani** [comment] 2016-08-25 14:33
OK, thanks a lot for your help in advices ;)
Have a lovely day
Cheers
